name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - feature/restrict-by-email
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            RUNTIME=hackmdio/runtime:14.21.2-083a4789
            BUILDPACK=hackmdio/buildpack:14.21.2-083a4789
          context: .
          file: deployments/Dockerfile
          tags: ghcr.io/yusukeiwaki/codimd:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
